# Generated by Django 4.2.27 on 2026-01-16 08:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pehchan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="donor_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="donor_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="donor_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="google_form_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="anonymous_donation_receipts/"
            ),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="anonymousdonation",
            name="wants_receipt",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("read", "Read"),
                    ("replied", "Replied"),
                    ("archived", "Archived"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("travel", "Travel"),
                    ("salary", "Salary"),
                    ("marketing", "Marketing"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="related_donation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pehchan.moneydonation",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="related_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pehchan.expense",
            ),
        ),
    ]
