# Generated by Django 4.2.25 on 2025-10-26 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pehchan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('material', 'Material Donation'), ('money', 'Money Donation')], max_length=20)),
                ('certificate_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(default='Pehchan NGO', max_length=200)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or appreciation message')),
                ('file', models.FileField(blank=True, null=True, upload_to='donor_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pehchan.materialdonation')),
                ('money_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pehchan.moneydonation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Certificate',
                'verbose_name_plural': 'Donor Certificates',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
