# Generated by Django 4.2.25 on 2025-10-26 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pehchan', '0002_donorcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', help_text='Current status of the message', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level for handling this message', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for team members (not visible to sender)', null=True)),
                ('response', models.TextField(blank=True, help_text='Response sent to the person', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='Date and time when response was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sender (for security)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser information (for analytics)', null=True)),
                ('responded_by', models.ForeignKey(blank=True, help_text='Admin who responded to this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='pehchan_con_created_06050b_idx'), models.Index(fields=['status'], name='pehchan_con_status_5b0866_idx'), models.Index(fields=['priority'], name='pehchan_con_priorit_6ebd6a_idx'), models.Index(fields=['email'], name='pehchan_con_email_8ed497_idx')],
            },
        ),
    ]
