# Generated by Django 4.2.27 on 2026-02-08 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pehchan", "0002_alter_expense_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialdonation",
            name="contact_number",
            field=models.CharField(
                default="0000000000",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Contact number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="moneydonation",
            name="contact_number",
            field=models.CharField(
                default="0000000000",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Contact number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
