# Generated by Django 4.2.27 on 2026-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pehchan", "0003_materialdonation_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneydonation",
            name="status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("verified", "Verified"),
                    ("declined", "Declined"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
    ]
