# Generated by Django 4.2.20 on 2025-10-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, help_text='Donor name (optional for anonymous)', max_length=200, null=True)),
                ('donor_email', models.EmailField(blank=True, help_text='Email for receipt (optional)', max_length=254, null=True)),
                ('donor_phone', models.CharField(blank=True, help_text='Contact number (optional)', max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10)),
                ('transaction_id', models.CharField(blank=True, help_text='UPI transaction ID', max_length=100, null=True)),
                ('wants_receipt', models.BooleanField(default=False, help_text='Donor wants a receipt marked as Anonymous')),
                ('message', models.TextField(blank=True, help_text='Additional message from donor', null=True)),
                ('google_form_submitted', models.BooleanField(default=False, help_text='Has the donor submitted the Google Form?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of donor', null=True)),
            ],
            options={
                'verbose_name': 'Anonymous Donation',
                'verbose_name_plural': 'Anonymous Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
