# Generated by Django 4.2.20 on 2025-11-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousdonation',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload payment receipt', null=True, upload_to='anonymous_donation_receipts/'),
        ),
    ]
