# Generated by Django 4.2.27 on 2026-02-08 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pehchan", "0005_eventvolunteer_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifetimevolunteer",
            name="contact_number",
            field=models.CharField(
                default="0000000000",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Contact number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
