# Generated by Django 4.2.30 on 2026-07-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0007_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fundraising_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target amount to raise for this event', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lifetimevolunteer',
            name='attended',
            field=models.BooleanField(default=False, help_text='Check if the volunteer actually attended the event'),
        ),
        migrations.AddField(
            model_name='moneydonation',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this donation to a specific event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_donations', to='pehchan.event'),
        ),
    ]
