# Generated by Django 4.2.30 on 2026-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0008_event_fundraising_goal_event_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifetimevolunteer',
            name='attended',
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='attended',
            field=models.BooleanField(default=False, help_text='Did the volunteer actually attend the event?'),
        ),
    ]
